### ISSUE TITLE
Jam Hat buzzer error when using RPi Zero with RPi Desktop USB

### ISSUE THREAD

**Issue by cst-msub** [modmypi/Jam-HAT#3]
The buzzer command returns an integer error when trying to play a Tone.

Any suggestions?

**Comment by tuftii** [comment]
Could you please give a sample of the code you used and the error given from Python when the buzzer didn't play?

**Comment by cst-msub** [comment]
When running this program I don't have sound on startup and when I press a button the error listed below appears in the Shell.

Here is the code from GitHub:

# Import the necessary libraries.
# gpiozero contains our JamHat object.
from gpiozero import JamHat
from time import sleep

# Initialise the JamHat object.
jh = JamHat()

# Build an array of notes in hertz.
NOTES = [440.000, 391.995, 349.228, 329.628, 293.665, 261.626]

# Initialise our counters for the while loop below.
i = 0
j = 0
note = 0

# Setup a try/except block so we can run until CTRL+C is pressed.
try:
    while True:
        if(jh.button_2.is_pressed):
            # If the second button is pressed, increment the counter into our NOTES array.
            note = (note + 1) % 6
            # Using modular arithmetic, decrease the light counter.
            # Our lights are in a matrix with rows 0-1 and columns 0-2.
            # Eg. [0][1] is the top yellow LED.
            if(j == 2):
                # If we're at the end of the row, increment to the next row.
                i = (i + 1) % 2
            # Increment the column.
            j = (j + 1) % 3
            sleep(0.1)
        # Turn off the hat
        jh.off()
        # Turn on the next light in the i/jth slot.
        jh[i][j].on()

        if(jh.button_1.is_pressed):
            # If the button is pressed, play the current note from NOTES out of the buzzer.
            jh.buzzer.play(NOTES[note])
        sleep(0.1)

except KeyboardInterrupt:
    # If someone presses CTRL+C, close the JamHat, freeing of the Pins for use elsewhere.
    jh.close()

Here is the error in the Shell:

Traceback (most recent call last):
  File "/home/pi/JamHat-debug.py", line 39, in <module>
    jh.buzzer.play(NOTES[note])
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 694, in play
    self.pwm_device.pin.frequency = freq
  File "/usr/lib/python3/dist-packages/gpiozero/pins/__init__.py", line 358, in <lambda>
    lambda self, value: self._set_frequency(value),
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pigpio.py", line 298, in _set_frequency
    self.factory.connection.set_PWM_frequency(self.number, value)
  File "/usr/lib/python3/dist-packages/pigpio.py", line 1542, in set_PWM_frequency
    _pigpio_command(self.sl, _PI_CMD_PFS, user_gpio, frequency))
  File "/usr/lib/python3/dist-packages/pigpio.py", line 983, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
struct.error: required argument is not an integer

**Comment by cst-msub** [comment]
It is spaced properly, the indents got removed during the paste.

**Comment by tuftii** [comment]
I think you've copied the code in and pasted it directly, meaning GitHub reads it as Markdown (hence all the hashes get read as headers and not Python comments).

This looks like the button_led_piezo.py script from the library, can you confirm? Can you please paste the code in using Markdown's formatting so I can read the script a little easier?

You say you don't have sound on startup... can you try the following short script to check the buzzer/leds are working in the first place:

```
from gpiozero import JamHat
from time import sleep

jh = JamHat()

jh.on()
sleep(1)
jh.off()
jh.close()
```

Using this all LEDs and the buzzer should come on.

**Comment by cst-msub** [comment]
No LEDs or Buzzer - Here is error output:

    >>>
    
     %Run githubT01.py
    Traceback (most recent call last):
      File "/home/pi/githubT01.py", line 6, in <module>
        jh.on()
      File "/usr/lib/python3/dist-packages/gpiozero/boards.py", line 2231, in on
        self.buzzer.value = 0
      File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 432, in __setattr__
        return super(CompositeDevice, self).__setattr__(name, value)
      File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 148, in __setattr__
        return super(GPIOBase, self).__setattr__(name, value)
      File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 746, in value
        self.pwm_device.pin.frequency = freq
      File "/usr/lib/python3/dist-packages/gpiozero/pins/__init__.py", line 358, in <lambda>
        lambda self, value: self._set_frequency(value),
      File "/usr/lib/python3/dist-packages/gpiozero/pins/pigpio.py", line 298, in _set_frequency
        self.factory.connection.set_PWM_frequency(self.number, value)
      File "/usr/lib/python3/dist-packages/pigpio.py", line 1542, in set_PWM_frequency
        _pigpio_command(self.sl, _PI_CMD_PFS, user_gpio, frequency))
      File "/usr/lib/python3/dist-packages/pigpio.py", line 983, in _pigpio_command
        sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
    struct.error: required argument is not an integer`

I hope that helps.

**Comment by tuftii** [comment]
It looks like the Pin Factory being used is PiGPIOFactory which isn't supported by the underlying Tonal Buzzer class used to set up the buzzer, see the GPIOZero docs: https://gpiozero.readthedocs.io/en/stable/api_output.html#tonalbuzzer

Are you running the pins remotely using a daemon? If so, can you confirm the board works by using the code directly on the Pi itself.

> 
> ```
> from gpiozero import JamHat
> from time import sleep
> 
> jh = JamHat()
> 
> jh.on()
> sleep(1)
> jh.off()
> jh.close()
> ```
> 
> Using this all LEDs and the buzzer should come on.

**Comment by cst-msub** [comment]
The Pin Factory was what I thought before I posted. I am using the Raspberry Pi Desktop image with a RPi Zero connected by USB to provide me with remote GPIO access on the Zero. I will wait to add the buzzer in my presentations and curriculum until a fix/solution is developed. Thank you for the response and confirming my thoughts.

**Comment by tuftii** [comment]
No worries. I'm going to close this off as this is a GPIO Zero/PiGPIO issue and beyond the scope of this Jam Hat library. I couldn't find a corresponding issue in the GPIO Zero repo so feel free to raise one if you like.
